# ============================================================================
# VERIFY ENVIRONMENT & GENERATE REQUIREMENTS.TXT (No pkg_resources)
# ============================================================================

import subprocess
import sys
import importlib

# ============================================================================
# PART 1: CHECK CRITICAL PACKAGES
# ============================================================================

print("="*60)
print("🔍 VERIFYING ENVIRONMENT VERSIONS")
print("="*60)

critical_packages = [
    ('fastapi', 'fastapi'),
    ('uvicorn', 'uvicorn'),
    ('joblib', 'joblib'),
    ('pandas', 'pandas'),
    ('numpy', 'numpy'),
    ('scikit-learn', 'sklearn'),
    ('sentence-transformers', 'sentence_transformers'),
    ('torch', 'torch'),
    ('pydantic', 'pydantic'),
    ('python-multipart', 'python_multipart'),
    ('openai-whisper', 'whisper'),
    ('transformers', 'transformers'),
    ('huggingface-hub', 'huggingface_hub'),
    ('xgboost', 'xgboost'),
]

versions = {}

def get_package_version(package_name):
    """Get package version using pip"""
    try:
        result = subprocess.run(
            [sys.executable, '-m', 'pip', 'show', package_name],
            capture_output=True,
            text=True
        )
        for line in result.stdout.split('\n'):
            if line.startswith('Version:'):
                return line.split(':', 1)[1].strip()
        return "unknown"
    except:
        return "unknown"

for pip_name, import_name in critical_packages:
    try:
        module = importlib.import_module(import_name)
        version = getattr(module, '__version__', None)
        if not version:
            version = get_package_version(pip_name)
        versions[pip_name] = version
        status = "✅"
    except ImportError:
        versions[pip_name] = "NOT INSTALLED"
        status = "❌"
    
    print(f"{status} {pip_name:<25} : {versions[pip_name]}")

print("="*60)

# ============================================================================
# PART 2: CHECK PYTHON VERSION
# ============================================================================

python_version = f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"
print(f"\n🐍 Python version: {python_version}")
print("="*60)

# ============================================================================
# PART 3: CHECK CRITICAL FUNCTIONALITY
# ============================================================================

print("\n🧪 TESTING CRITICAL FUNCTIONALITY:")
print("-"*40)

# Test 1: FastAPI import
try:
    from fastapi import FastAPI
    print("✅ FastAPI import OK")
except Exception as e:
    print(f"❌ FastAPI import failed: {e}")

# Test 2: Sentence Transformers
try:
    from sentence_transformers import SentenceTransformer
    print("✅ SentenceTransformer import OK")
except Exception as e:
    print(f"❌ SentenceTransformer import failed: {e}")

# Test 3: Whisper
try:
    import whisper
    print("✅ Whisper import OK")
except Exception as e:
    print(f"❌ Whisper import failed: {e}")

# Test 4: PyTorch
try:
    import torch
    print(f"✅ PyTorch {torch.__version__} OK (CUDA: {torch.cuda.is_available()})")
except Exception as e:
    print(f"❌ PyTorch import failed: {e}")

# Test 5: XGBoost (if used)
try:
    import xgboost
    print(f"✅ XGBoost {xgboost.__version__} OK")
except Exception as e:
    print(f"⚠️ XGBoost not installed (optional)")

# Test 6: joblib
try:
    import joblib
    print(f"✅ joblib {joblib.__version__} OK")
except Exception as e:
    print(f"❌ joblib import failed: {e}")

print("="*60)

# ============================================================================
# PART 4: GENERATE REQUIREMENTS.TXT
# ============================================================================

print("\n📝 GENERATING requirements.txt")
print("="*60)

# Only include packages that are actually installed
installed_packages = []
for package, version in versions.items():
    if version != "NOT INSTALLED" and version != "unknown":
        installed_packages.append(f"{package}=={version}")

# Write requirements file
with open('requirements.txt', 'w') as f:
    f.write(f"# Python {python_version}\n")
    f.write("# Generated by verify_environment.py\n")
    f.write("# ====================================\n\n")
    for pkg in sorted(installed_packages):
        f.write(f"{pkg}\n")

print(f"✅ Generated requirements.txt with {len(installed_packages)} packages")
print("\nContents:")
print("-"*40)
for pkg in sorted(installed_packages):
    print(f"  {pkg}")
print("-"*40)

# ============================================================================
# PART 5: CHECK FOR CONFLICTS
# ============================================================================

print("\n⚠️ CONFLICT CHECK:")
print("-"*40)

# Check numpy vs scikit-learn compatibility
if 'numpy' in versions and 'scikit-learn' in versions:
    numpy_ver = versions['numpy']
    if numpy_ver.startswith('2.'):
        print("⚠️ Warning: numpy 2.x may have compatibility issues")
    else:
        print("✅ numpy version OK")

# Check torch version
if 'torch' in versions:
    torch_ver = versions['torch']
    print(f"✅ torch {torch_ver}")

print("="*60)

# ============================================================================
# PART 6: QUICK TEST COMMANDS
# ============================================================================

print("\n🚀 QUICK TEST COMMANDS:")
print("-"*40)
print("\n# Test API locally:")
print("python app.py")
print("\n# Test health endpoint:")
print("curl http://localhost:8000/health")
print("\n# Test text recommendation:")
print('curl -X POST "http://localhost:8000/recommend" -H "Content-Type: application/json" -d "{\\"query\\": \\"acné\\", \\"top_k\\": 5}"')
print("\n# Test voice recommendation (with WAV file):")
print('curl -X POST "http://localhost:8000/recommend/voice" -F "audio=@test.wav"')
print("="*60)

print("\n✅ Verification complete!")